// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type Room struct {
	RoomID int64    `json:"room_id"`
	Member []string `json:"member"`
	Date   int32    `json:"date"`
	Time   int32    `json:"time"`
}

type User struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	Email     string        `json:"email"`
	Gender    string        `json:"gender"`
	CreatedAt time.Time     `json:"created_at"`
	RoomID    sql.NullInt32 `json:"room_id"`
}
