// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type Room struct {
	RoomID      int64     `json:"room_id"`
	Source      string    `json:"source"`
	Destination string    `json:"destination"`
	Member      []string  `json:"member"`
	Date        time.Time `json:"date"`
	Time        time.Time `json:"time"`
	IsFull      bool      `json:"is_full"`
}

type User struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	Email     string        `json:"email"`
	Gender    string        `json:"gender"`
	Item      []string      `json:"item"`
	CreatedAt time.Time     `json:"created_at"`
	RoomID    sql.NullInt64 `json:"room_id"`
}
